# Flujos de trabajo y ciclos

## Operadores lógicos

Se utilizan para realizar comparaciones o verificar la igualdad entre objetos. En python tenemos varios disponibles:

- `==` para la igualdad
- `!=` para la desigualdad
- `<` "menor que"
- `>` "mayor que"
- `<=` "menor o igual que"
- `>=` "mayor o igual que"

Estas comparaciones casi siempre se entiende que son para valores numéricos. Sin embargo, pueden aplicarse a textos, aunque solo consideran el orden alfabético en esos casos.

## Sentencias condicionales

### El `if`

Se utiliza para comprobar si una condición es cumplida, entonces se realiza una función o se evita, en consecuencia. Se define por la palabra reservada `if`, seguida por la condición a verificar y debe acompañarse de `:`, delante del cual se especifica la acción a realizar. Siempre va primero en las comparaciones lógicas.

```{python}
# Verificando existencias de pasta
pasta_necesaria = 200
pasta_disponible = 500

# Comparando cantidades
if pasta_necesaria <= pasta_disponible:
    print("Suficiente pasta.")
```

### El `elif`

Si la condición no se cumple, tenemos dos caminos a elegir: poner otra condición y verificar si esta se cumple o directamente especificar otra acción a realizar.

La sentencia `elif` nos permite lo primero. Por ejemplo, suponiendo que no tenemos suficiente pasta, podemos verificar si al menos tenemos una cantidad que nos permita raciones más pequeñas o menor cantidad de invitados:

```{python}
# Verificando existencias de pasta
pasta_necesaria = 500
pasta_disponible = 300

# Comparando cantidades
if pasta_necesaria <= pasta_disponible:
    print("Suficiente pasta.")
elif pasta_disponible >= 300:
    print("Prueba porciones menores.")
```

Podemos utilizar tantas sentencias `elif` como queramos, aunque siempre debe ir después de un `if`.

### El `else`

Si no se cumple ninguna condición, podemos especificar qué hacer. Ello se hace con el `else`. Supongamos una situación en la que ni siquiera tenemos la pasta suficiente para raciones pequeñas:

```{python}
# Verificando existencias de pasta
pasta_necesaria = 500
pasta_disponible = 200

# Comparando cantidades
if pasta_necesaria <= pasta_disponible:
    print("Suficiente pasta.")
elif pasta_disponible >= 300:
    print("Prueba porciones menores.")
else:
    print("No hay pasta suficiente.")
```

Solo podemos usar un `else` en el flujo y siempre debe ir al final, después de un `if` o `elif`.

## Ciclos `for`

### Sintaxis

La sintaxis consiste en lo siguiente: para cada `valor` dentro de la `secuencia`, ejecuta tal `acción`.

```python
for valor in secuencia:
    acción
```

La secuencia es algo iterable, como una lista o un diccionario; mientras el valor es un índice, al cual le podemos nombrar como queramos aunque un comodín muy común es `i`.

Partamos de una lista y vayamos recorriéndola para imprimir todos sus elementos por separado.

```{python}
# Creamos la lista
ingredientes = ["fusilli", "tomates", "ajo", "albahaca", "aceite de oliva", "sal"]
# Recorremos a través de cada elemento en la lista
for ingrediente in ingredientes:
    print(ingrediente)
```

Si deseamos iterar en un rango controlado, podemos introducir precisamente dicho rango:

```{python}
# Contaremos del 1 al 6
for ingrediente in range(1, 7):
    print("Agregando ingrediente", ingrediente)
```

### Ciclo condicional

Podemos agregarle condicionales a nuestro ciclo, partiendo de una lista de cantidades, naturalmente.

```{python}
# Creamos la lista
cantidades = [500, 400, 20, 15, 15, 7]

# Recorremos las cantidades en ciclo
for cantidad in cantidades:
    if cantidad >= 400:
        print("Alta cantidad")
    elif cantidad >= 200:
        print("Cantidad media")
    else:
        print("Baja cantidad")
```

### Ciclo en un diccionario

Utiliza la misma dinámica que en las anteriores estructuras, con excepción de que puede usar dos iteradores. Veamos cómo escalar las cantidades tras multiplicarlas por dos de manera iterada.

```{python}
# Creamos la receta
receta = {
          "fusilli": 500,
          "tomates": 400,
          "albahaca": 20,
          "ajo": 15,
          "aceite de oliva": 15,
          "sal": 7}

# Iteramos a través de sus elementos
# Para cada ingrediente y cantidad en la receta:
for ingrediente, cantidad in receta.items():
    # duplica la cantidad para escalarla
    cantidad_escalada = cantidad * 2

    # Imprime
    print(ingrediente, ":", cantidad_escalada, "g")
```

## Ciclo `while`

Contrario al bucle `for` que se ejecuta de acuerdo a unos límites que nosotros especificamos, el `while` estará funcionando mientras se cumplan las condiciones dadas en su codificación. Eso abre la posibilidad de ciclos infinitos o que terminan colapsando el equipo. Debemos ser muy cuidadosos con nuestros ciclos `while`.

Vamos a crear un ciclo `while` que se esté ejecutando mientras una variable sea menor a otra, pero es muy importante que hagamos que la primera comience a incrementarse para que así tenga que finalizar en algún momento nuestro ciclo.

```{python}
# Invitaciones confirmadas
confirmaciones = 10
# Número de asistentes
asistentes = 0

# Ciclo que cuenta los asistentes
while asistentes < confirmaciones:
    asistentes += 1
    print(asistentes, "invitados")

# Ciclo finalizado
print("Tenemos", asistentes, "asistentes llegando.")
```

### Bucles condicionales

Debemos verificar que tengamos suficiente cantidad de ingredientes antes de escalar nuestra receta. Usaremos un bucle `while` combinado con lógica condicional para comprobar las cantidades y proporcionar actualizaciones que resulten útiles.

También utilizaremos una variable que hará el seguimiento de cuantos ingredientes hemos verificado y otra que representa el número total de ingredientes de la receta.

```{python}
# Número de ingredientes
total_ingred = 7
# # Número de verificados
ingred_verificados = 0

# Creamos el bucle
# Mientras los verificados sean menos que el total
while ingred_verificados < total_ingred:
    # incrementamos el conteo
    ingred_verificados += 1
    # Si hay menos de 4 verificados
    if ingred_verificados < 4:
        # imprime lo que falta
        print("Falta más de la mitad")
    # Pero si hay 6 o menos:
    elif ingred_verificados <= 6:
        print("Casi terminamos")
    # Si no:
    else:
        print("Hemos terminado")
```

## El flujo de trabajo

Probemos la función de lista de la compra para el escalador de recetas. Antes de escalar, debemos comprobar si nos falta algún ingrediente.

Retomemos los diccionarios necesarios:

```{python}
# Cantidades necesarias
receta = {"pasta": 500,
          "tomates": 400,
          "albahaca": 20,
          "ajo": 15,
          "aceite de oliva": 30,
          "sal": 10}

# Cantidades disponibles
inventario = {"pasta": 100,
              "tomates": 1500,
              "albahaca": 20,
              "ajo": 10,
              "aceite de oliva": 10,
              "sal": 150}
```

```{python}
# Creamos una lista para las compras
lista_compras = []

# Recorremos el diccionario Receta para acceder a todo
for ingrediente, cantidad in receta.items():
    # Verificamos si necesitamos:
    if cantidad > inventario[ingrediente]:
        # agrega el ingrediente a la lista de compras
        lista_compras.append(ingrediente)

# Imprime la lista de compras
print(lista_compras)

```





