# El ecosistema Python

## Funciones predefinidas

Existen varias funciones predefinidas en Python, las cuales nos permiten construir programas con menos código. Veamos algunas que resultan ser muy útiles.

Para encontrar las cantidades mayores o menores:

```{python}
# Lista de tiempos
tiempos_preparación = [19.23, 15.67, 48.57, 23.45, 12.06, 34.56, 45.67]

# Encontremos el mmayor tiempo
print(max(tiempos_preparación))
```

```{python}
# Encontremos el menor
print(min(tiempos_preparación))
```

```{python}
# Calculemos el total de tiempos
print(sum(tiempos_preparación))
```

```{python}
# Contemos cuántos tiempos tenemos
print(len(tiempos_preparación))
```

```{python}
# Redondeemos la sumatoria a dos decimales
print(round(sum(tiempos_preparación),2))
```

```{python}
# Calculemos el promedio de tiempos
print(sum(tiempos_preparación) / len(tiempos_preparación))
```

```{python}
# Ordenemos los tiempos
print(sorted(tiempos_preparación))
```

Aunque también se pueden ordenar caracteres, de manera alfabética, claro.

```{python}
print(sorted("Juan"))
```

## Módulos

Los módulos son programas Python almacenados en archivos `.py`, los cuales contienen funciones y atributos e incluso otros módulos. Esto nos permite evitar código que ya existe.

Hay cerca de 200 módulos predefinidos. Uno muy conocido es `os`, el cual se usa para interactuar con el sistema operativo, verificar la carpeta actual, enlistar archivos disponibles y acceder a variables de entorno.

### Importar un módulo

```{python}
# Importemos os
import os

# Revisemos su tipo
print(type(os))
```

### Encontrando información

Podemos revisar la documentación para acceder a información sobre los módulos.

```python
# Esto arrojará mucho texto
print(help(os))
```

### El directorio de trabajo

```python
# Obteniéndolo
print(os.getcwd())
# O asignándolo a una variable
carpeta_trabajo = os.getcwd()
```

```python
# Cambiando el directorio
os.chdir("home/Descargas")
# Verificar
print(os.getcwd())
```

### Atributos de un módulo

Los atributos devuelven valores mientras las funciones ejecutan tareas. Los atributos no llevan paréntesis. Obtengamos la variable de entorno:

```python
# Obtener el entorno local
print(os.environ)
```

