# Manipulando tipos de datos

## Cadenas

Ya se había mencionado que se prefiere utilizar dobles comillas para el trabajo con texto, esto para evitar problemas con el apóstrofe que también es la comillla simple.

Pero también podemos utilizar las triples comillas, lo que nos permite escribir cadenas de texto de varias líneas. Probemos con una receta para nuestro proyecto:

```{python}
instrucciones_receta = """1. Toma un recipiente grande de agua con sal hirviendo y cocina la pasta
2. Calienta el aceite de oliva en un sartén y sofríe el ajo hasta que aromatice
3. Agrega jitomates picados y cocínalos por 10 minutos
4. Mezcla la pasta cocinada con la salsa de tomate y sírvase
"""
```

Ahora veamos cómo queda:

```{python}
print(instrucciones_receta)
```

### Métodos

En Python usamos métodos, los cuales son funciones disponibles solo para ciertos tipos de datos. Algunos métodos útiles para texto se abordan a continuación.

Un método para reemplazar texto es `.replace()`.

```{python}
# Una pasta genérica...
tipo_pasta = "pasta"
# que mostramos
print(tipo_pasta)
```

Pongamos un nombre más claro:

```{python}
# Cambiamos el nombre
tipo_pasta = tipo_pasta.replace("pasta", "pasta fusilli")
# Volvemos a imprimir
print(tipo_pasta)
```

Podemos cambiar el texto a minúsculas o mayúsculas:

```{python}
# Declaramos el primer ingrediente
ingrediente_01 = "Jitomate"
# Lo cambiamos a minúsculas
ingrediente_01 = ingrediente_01.lower()
print(ingrediente_01)
```

```{python}
# Declaramos un nombre de receta
receta_01 = "fideo"
# Cambiamos a mayúsculas
receta_01 = receta_01.upper()
print(receta_01)
```

## Listas

Las listas nos permiten almacenar varios valores en una sola variable y pueden contener cualquier combinación de tipos de datos.

Crearemos unas cuantas listas para almacenar los ingredientes y las cantidades en gramos.

```{python}
# Creamos la lista de ingredientes
ingredientes = ["fusilli", "jitomates", "ajo", "albahacaa", "aceite de oliva", "sal"]
# Mostramos la lista
print(ingredientes)
```

```{python}
# Ahora creamos la lista con las cantidades
cantidades = [500, 400, 15, 20, 30, 10]
# y la mostramos
print(cantidades)
```

Python ordena los elementos de una lista contando desde `0`, por lo que el primer elemento siempre será el elemento `0`.

### Accediendo a los elementos de una lista

Se utiliza el nombre de la lista y entre corchetes colocamos el índice del elemento a buscar. Por ejemplo, para acceder al primer elemento de los ingredientes hacemos:

```{python}
# Seleccionar el primer elemento
print(ingredientes[0])
```

En caso de desear acceder al último dato en una lista, podemos escribir el índice del mismo o bien, escribir `-1`:

```{python}
# Seleccionamos el último elemento
print(ingredientes[5])
# Igual, pero con -1
print(ingredientes[-1])
```

Si deseamos acceder a varios elementos en Python, debemos tener en cuenta que no incluye el índice "por derecha". Para ilustrarlo, tratemos de acceder al segundo y tercer elemento en lista:

```{python}
# Accedemos al tercero agregando 1 al índice
print(ingredientes[1:3])
```

¿Pero qué pasa con el índice "por izquierda"?

```{python}
# Seleccionemos desde el cuarto elemento
print(ingredientes[3:])
```

```{python}
# Obtengamos los primeros 3 elementos
print(ingredientes[:3])
```

También podemos acceder alternando a los objetos dentro de la lista:

```{python}
# Accedamos cada dos elementos
print(ingredientes[::2])
# Lo mismo pero indicando a partir de cuál
print(ingredientes[1::2])
# Contando cada tercer elemento
print(ingredientes[1::3])
```

## Diccionarios

Son listas que contienen el listado de elementos pero además incluyen un valor asignado a cada uno de ellos. De ahí el nombre de diccionarios: un elemento y su definición. En el proyecto de escalador de recetas necesitamos un diccionario que enlace los ingredientes con sus cantidades.

### Creando diccionarios

Se utilizan las llaves`{}` para el contenido, colocando primero el nombre (la clave) y luego su correspondiente valor.

```{python}
# Creando el diccionario para una receta
receta = {"pasta": 500,
          "tomates": 400,
          "ajo": 15,
          "albahaca": 20,
          "aceite de oliva": 30,
          "sal": 5}
```

### Accediendo a los datos

Los diccionarios están ordenados y permiten acceder a sus valores por referenciar la clave. Por ejemplo, accedamos a la cantidad de pasta:

```{python}
# ¿Cuánta pasta necesitamos?
print(receta["pasta"])
```

Si queremos acceder a todos los valores, basta con

```{python}
# Obtener todos los valores
print(receta.values())
```

Y para las claves:

```{python}
# Leer todas las claves
print(receta.keys())
```

Si lo que queremos es mostrar todo el diccionario, tenemos dos formas, verlo completo o mostrar cada par de elementos organizado.

```{python}
# Mostrar todo el diccionario
print(receta)
```

```{python}
# Obtener todos los objetos
print(receta.items())
```

### Editando objetos

Para agregar un nuevo objeto basta con hacer referencia al nuevo elemento y asignarle su valor:

```{python}
# Agregar el parmesano
receta["parmesano"] = 50
```

Si queremos actualizar un objeto, seguimos el mismo proceso, pero obviamente con una clave ya existente en el diccionario:

```{python}
# Cambiar la cantidad de pasta
receta["pasta"] = 800
```

## Conjuntos y tuplas

### Los conjuntos

Contienen datos únicos cuyos valores pueden ser agregados y eliminados, pero no editados. Son ideales para identificar y remover duplicados, ya que además son rápidos para realizar búsquedas en ellos. Sin embargo, no es posible indexarlos, solo ordenarlos.

Un conjunto se crea utilizando también `{}`, pero sin utikizar los dos puntos `:`, ya que no son diccionarios.

```{python}
# Creando un conjunto
conjunto_ingredientes = {"pasta", "tomates", "albahaca", "ajo"}
# Mostrando el conjunto
print(conjunto_ingredientes)
```

Un conjunto puede ordenarse con

```{python}
# Mostrar un conjunto ordenado
print(sorted(conjunto_ingredientes))
```

Una lista puede convertirse en un conjunto con la función `set()`.

### Las tuplas

Son inmutables: no permiten agregar, remover ni editar valores aunque sí ordenarse e indexarse. Son útiles para almacenar información o identificadores.

Una tupla puede crearse con `()`:

```{python}
# Creando una tupla
porciones = (1, 2, 4, 6)
```

Una estructura de datos puede convertirse en una tupla con la sentencia `tuple()`.

La indexación de una tupla es igual a otras estructuras:

```{python}
# Accediendo al segundo elemento
print(porciones[1])
```



